name: 2-feladat

on:
  push 

jobs:
  Lekodolhatok:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: g++ -std=c++17 *.cpp
      - run: ./run-test.sh
      - name: Install tools
        run: sudo apt-get install -y valgrind cppcheck
      - name: Gpp Error
        run: g++ -Wall -Werror *.cpp
      - name: Valgrind Error
        run: valgrind --error-exitcode=1 ./a.out units/kakarott.json units/makarott.json units/vakarott.json
      - name: Cppchecks Error
        run: cppcheck *.cpp --enable=warning --error-exitcode=1
      - name: Error List
        run: cppcheck *.cpp --enable=warning --output-file=list.txt
      - name: Artifacting
        uses: actions/upload-artifact@v2
        with:
          name: lists
          path: ./list.txt 
